version: '3'
services:
  client-container:
    image: client-image
    build: ./client
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
    container_name: client-container

  spring-container:
    image: springboot-image
    build: ./spring-ws-server
    ports: 
      - "8080:8080"
    container_name: springboot-container
